config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: {   registrations: 'users/registrations',
    sessions: 'users/sessions' }
  
  root to: 'lp#index'
  resources :tweets do
    resources :comments,only: [:index,:create] do
    end
      resources :tweet_likes, only: [:index,:create,:destroy]
  end
  resources :user,only: [:show,:edit,:update] do
    resources :chat_room, only: [:new,:create] do
      resources :chats, only: [:index, :create]
    end
  end
  resources :operations , only: [:index,:edit]
  resources :researches do
    resources :research_comments, only: [:index,:create]
    resources :research_likes, only: [:index,:create,:destroy]
    collection do
      get 'my_research'
      get 'search'
      get 'my_search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :chats
  has_many :room_users
  has_many :users, through: :room_users
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  belongs_to :tweet
end

app/models/research.rb
class Research < ApplicationRecord
  validates :research_url,presence: true
  validates :research_title,presence: true,length: { maximum: 50 }
  validates :research_summary,presence: true,length: { maximum: 500 }
  belongs_to :user
  has_many :research_comments
  has_many :research_likes

  def self.search(search_key)
      Research.where('research_title LIKE(?)', "%#{search_key}%")
  end 

  def self.my_search(search_key,current_user_id)
    Research.where('research_title LIKE(?)', "%#{search_key}%").where('user_id LIKE(?)', "%#{current_user_id}%")
end 

end

app/models/research_comment.rb
class ResearchComment < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  belongs_to :research
end

app/models/research_like.rb
class ResearchLike < ApplicationRecord
  belongs_to :user
  belongs_to :research
  validates_uniqueness_of :research_id, scope: :user_id
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :tweet, presence: true
  belongs_to :user
  has_many :comments
  has_many :tweet_likes
end

app/models/tweet_like.rb
class TweetLike < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets,dependent: :destroy
  has_many :researches,dependent: :destroy
  has_one_attached :user_icon,dependent: :destroy
  has_one_attached :user_identification,dependent: :destroy
  has_many :comments,dependent: :destroy
  has_many :research_comments,dependent: :destroy
  has_many :research_likes,dependent: :destroy
  has_many :tweet_likes,dependent: :destroy
  has_many :room_users
  has_many :chat_rooms, through: :room_users
  has_many :chats
  validates :Nickname, presence: true,uniqueness: true,length: { maximum: 15 }
  validates :password, length: { maximum: 30 }
  validates :password_confirmation, length: { maximum: 30 }
  validates :hobby, length: { maximum: 100 }
  validates :aWord, length: { maximum: 100 }

  def already_liked?(research)
    self.research_likes.exists?(research_id: research.id)
  end

  def tweet_already_liked?(tweet)
    self.tweet_likes.exists?(tweet_id: tweet.id)
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_action :set_tweet, only: :index
  before_action :return_index, except: :index 

  def index
  @comment = Comment.new
  @comments = @tweet.comments.includes(:user)
  end  

  def create
    Comment.create(comment_params)
    redirect_to tweet_comments_path(comment_params[:tweet_id]) 
  end

  private

  def return_index
    unless user_signed_in?
      redirect_to "/"
    end
  end

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
  end

  def set_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end

end

app/controllers/lp_controller.rb
class LpController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_room_helper.rb
module ChatRoomHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lp_helper.rb
module LpHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/helpers/researches_helper.rb
module ResearchesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/_commentindex.html.erb
          <div class="content-post-area">
            <div class="content-post" >
              <div class="content-post-left">
               <% if comment.user.user_icon.presence %>
                <%= link_to image_tag(comment.user.user_icon, class: 'icon' )  , user_path(comment.user_id)  %>
               <% else %>
                 <%= link_to image_tag("/images/icon.png", class: 'headder-account' )  , user_path(comment.user_id)  %>
               <% end %>
              </div>
              <div class="content-post-center">
                <div class="content-post-center-top">
                  <% if comment.user.student_or_coach == "coach" %>
                    <%= image_tag("/images/coach.png", class: 'coach_icon' ) %>
                  <% end %>
                  <p class="contributor-name"><%= comment.user.Nickname %></p>
                  <p class="time"><%= comment.created_at.in_time_zone("Tokyo") %></p>
                </div>
                <p class="tweet-string"><%= comment.text %></p>
              </div>
            </div>
              <% if comment.user.student_or_coach == "coach" && current_user.id == comment.tweet.user_id && current_user.student_or_coach == "student" %>
                <div class="comment-content-post-bottom">
                    <%= link_to image_tag("/images/researcher.png", class:"tweet-comment-post"),user_path(comment.user.id) %>
                  <div class="challenge-button">
                    <p>この先生と一緒に研究する！</p>
                  </div>
                </div>
              <% end %>
          </div>

app/views/comments/index.html.erb
    <%= render partial: "tweets/header" %>
    <div class="middle-content">
      <%= render partial: "tweets/sidebar" %>
      <div class="main">
        <div class="contents-row">
          <%= render partial: "tweets/postindex", locals: { tweet: @tweet } %>
          <div class="comment-index">
            <% if user_signed_in? %>
              <%= form_with(model: [@tweet, @comment], local: true) do |form| %>
                <%= form.text_area :text, placeholder: "コメントする", rows: "2", class: "comment-content-form" %>
                <%= form.submit "投稿する", class: "comment-submit" %><br><br>
              <%end%>
            <%else%>
              <strong><p>※※※　コメントの投稿には新規登録/ログインが必要です　※※※</p></strong>
            <%end%>
             <%= link_to "戻る", tweets_path, class:  "research-send-back" %> 
            <div class="comments">
              <h2>【コメント一覧】</h2>
              <% @comments.each do |comment| %>
               <% if comment.user.present? %>
                <p>
                  <%= render partial: "commentindex", locals: { comment: comment } %>
                </p>
               <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

    </div>

    <%= render partial: "tweets/footer" %>