config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: {   registrations: 'users/registrations',
    sessions: 'users/sessions' }
  
  root to: 'lp#index'
  resources :tweets do
    resources :comments,only: [:index,:create] do
    end
      resources :tweet_likes, only: [:index,:create,:destroy]
  end
  resources :user,only: [:show,:edit,:update] do
    resources :chat_room, only: [:new,:create] do
      resources :chats, only: [:index, :create]
    end
  end
  resources :operations , only: [:index,:edit]
  resources :researches do
    resources :research_comments, only: [:index,:create]
    resources :research_likes, only: [:index,:create,:destroy]
    collection do
      get 'my_research'
      get 'search'
      get 'my_search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :chats
  has_many :room_users
  has_many :users, through: :room_users
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  belongs_to :tweet
end

app/models/research.rb
class Research < ApplicationRecord
  validates :research_url,presence: true
  validates :research_title,presence: true,length: { maximum: 50 }
  validates :research_summary,presence: true,length: { maximum: 500 }
  belongs_to :user
  has_many :research_comments
  has_many :research_likes

  def self.search(search_key)
      Research.where('research_title LIKE(?)', "%#{search_key}%")
  end 

  def self.my_search(search_key,current_user_id)
    Research.where('research_title LIKE(?)', "%#{search_key}%").where('user_id LIKE(?)', "%#{current_user_id}%")
end 

end

app/models/research_comment.rb
class ResearchComment < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  belongs_to :research
end

app/models/research_like.rb
class ResearchLike < ApplicationRecord
  belongs_to :user
  belongs_to :research
  validates_uniqueness_of :research_id, scope: :user_id
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :tweet, presence: true
  belongs_to :user
  has_many :comments
  has_many :tweet_likes
end

app/models/tweet_like.rb
class TweetLike < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets,dependent: :destroy
  has_many :researches,dependent: :destroy
  has_one_attached :user_icon,dependent: :destroy
  has_one_attached :user_identification,dependent: :destroy
  has_many :comments,dependent: :destroy
  has_many :research_comments,dependent: :destroy
  has_many :research_likes,dependent: :destroy
  has_many :tweet_likes,dependent: :destroy
  has_many :room_users
  has_many :chat_rooms, through: :room_users
  has_many :chats
  validates :Nickname, presence: true,uniqueness: true,length: { maximum: 15 }
  validates :password, length: { maximum: 30 }
  validates :password_confirmation, length: { maximum: 30 }
  validates :hobby, length: { maximum: 100 }
  validates :aWord, length: { maximum: 100 }

  def already_liked?(research)
    self.research_likes.exists?(research_id: research.id)
  end

  def tweet_already_liked?(tweet)
    self.tweet_likes.exists?(tweet_id: tweet.id)
  end


end

app/controllers/lp_controller.rb
class LpController < ApplicationController

  def index
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :show]
  before_action :return_index, except: [:index,:show]

  def index
    @tweets = Tweet.all.order(created_at: :desc)
    @tweet = Tweet.new
  end

  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(tweet_params)
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
  end

  def edit
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params)
  end

  def show
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
    @likes = @tweet.tweet_likes.includes(:user)  
  end

  private

  def return_index
    unless user_signed_in?
      redirect_to "/"
    end
  end

  def tweet_params
    params.require(:tweet).permit(:tweet).merge(user_id:current_user.id)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_room_helper.rb
module ChatRoomHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lp_helper.rb
module LpHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/helpers/researches_helper.rb
module ResearchesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/tweets/_footer.html.erb
    <footer>
    </footer>

app/views/tweets/_header.html.erb
    <header>
      <div class="headder-content">
        <div class="headder-left">
           <%= link_to image_tag("/images/research1.png", class: 'headder-logo' )  , tweets_path  %>
           <%= link_to "ツクッター", tweets_path, class: "headder-name" %>
        </div>
        <div class="headder-right">
         <% if user_signed_in? %>
          <% if current_user.user_icon.presence %>
            <div>
             <%= link_to image_tag(current_user.user_icon, class: 'icon' )  , edit_user_registration_path  %>
            </div>
          <% else %>  
           <div>    
             <%= link_to image_tag("/images/icon.png", class: 'headder-account' )  , edit_user_registration_path  %>
           </div>
          <% end %> 
          <% if current_user.student_or_coach == "coach" %>
            <%= link_to image_tag("/images/coach.png", class: 'coach_icon' )  , edit_user_registration_path  %>
          <% end %>
           <div ><%= link_to current_user.Nickname , edit_user_registration_path ,class: "account-name"   %></div>
           <div class="logout"><%= link_to "ログアウト", destroy_user_session_path, method: :delete,class:  "btn btn--blue btn--shadow" %></div>
           
         <% end %>
         <% unless user_signed_in? %>
            <div class="unlogin_right">
               <%= link_to "ログイン", new_user_session_path, class: "btn btn--orange btn--shadow" %>
               <%= link_to "新規登録", new_user_registration_path, class:  "btn btn--blue btn--shadow" %>
            </div>
         <% end %>
        </div>
      </div>
    </header>

app/views/tweets/_postfunction.html.erb
        <div class="post-function">
         <% if user_signed_in? %>
           <% if current_user.user_icon.presence %>
            <div>
             <%= link_to image_tag(current_user.user_icon, class: 'icon' )  , tweets_path  %>
            </div>
          <% else %>  
           <div>    
             <%= link_to image_tag("/images/icon.png", class: 'account-icon' )  , tweets_path  %>
           </div>
          <% end %> 
          <%= form_with(model: @tweet, local: true) do |form| %>
            <%= form.text_area :tweet,placeholder: "面白いことや、不思議に思ったことはあったかな？", class: "tweet-content-form" %>
            <%= form.submit "つぶやく", class: "tweet-send" %>
          <%end%>
         <% end %>
        </div>        

app/views/tweets/_postindex.html.erb
          <div class="content-post-area">
            <div class="content-post" >
              <div class="content-post-left">
               <% if tweet.user.user_icon.presence %>
                <%= link_to image_tag(tweet.user.user_icon, class: 'icon' )  , tweets_path  %>
               <% else %>
                 <%= link_to image_tag("/images/icon.png", class: 'headder-account' )  , tweets_path  %>
               <% end %>
              </div>
              <div class="content-post-center">
                <div class="content-post-center-top">
                  <% if tweet.user.student_or_coach == "coach" %>
                    <%= image_tag("/images/coach.png", class: 'coach_icon' ) %>
                  <% end %>
                  <p class="contributor-name"><%= tweet.user.Nickname %></p>
                  <p class="time"><%= tweet.created_at.in_time_zone("Tokyo") %></p>
                </div>
                <p class="tweet-string"><%= tweet.tweet %></p>
                
              </div>
              <div class="content-post-right">
                <%= image_tag '/images/humbergerbutton.png', class: "humbergerbutton" %>
                <ul class="more_list">
                  <li><%= link_to '詳細', tweet_path(tweet.id), method: :get, class: "humberger_list" %></li>
                  <% if user_signed_in? %>
                   <% if tweet.user.id == current_user.id %>
                    <li><%= link_to '編集', edit_tweet_path(tweet.id), method: :get, class: "humberger_list" %></li>
                    <li><%= link_to '削除', tweet_path(tweet.id), method: :delete, class: "humberger_list" %></li>
                   <% end %>
                  <% end %>
                </ul>
              </div>
            </div>
            <div class="content-post-bottom">
              <div class="tweet-good-area">
                <% if user_signed_in? %>
                  <% if current_user.tweet_already_liked?(tweet) %>
                    <%= link_to image_tag("/images/heart.png", class: 'tweet-good' )  , tweet_tweet_like_path(tweet.id,current_user.id), method: :delete  %> 
                  <% else %>
                    <%= link_to image_tag("/images/heart.png", class: 'tweet-good-opa' )  , tweet_tweet_likes_path(tweet.id), method: :post   %>
                  <% end %> 
                  <% end %>
                  <% unless user_signed_in? %>
                   <%= link_to image_tag("/images/heart.png", class: 'tweet-good-opa' )  , tweet_tweet_likes_path(tweet.id)  %>
                  <% end %>
              </div>
              <div class="tweet-comment-area">
                <%= link_to image_tag("/images/comment.png", class:"tweet-comment"),tweet_comments_path(tweet.id) %>
              </div>
            </div>
          </div>

app/views/tweets/_sidebar.html.erb
      <div class="side-bar">
        <div class="tweet-content">
          <div class="tweet-content-top">
            <b class="top-item">呟き</b>
          </div>
              <ul>
                 <li><%= link_to "タイムライン", tweets_path, class: "side-bar-content" %></li>
                <% if user_signed_in? %>
                  <li><a class="side-bar-content"  href="/tweets/new">呟く</a></li>
                  <li><%= link_to "My呟き", "/user/#{current_user.id}", class: "mytweet" %></li>
                <% end %>
              </ul>
        </div>
        <div class="research-content">
          <div class="research-content-top">
            <b class="top-item">研究</b>
          </div>
            <ul>
              <li><%= link_to "タイムライン", researches_path, class: "side-bar-content" %></li>
              <% if user_signed_in? %>  
                <li><%= link_to "研究を投稿する", new_research_path, class: "side-bar-content" %></li>
                <li><%= link_to "My研究", my_research_researches_path, class: "side-bar-content" %></li>
              <% end %>
            </ul>
        </div>
        <% if user_signed_in? %>
        <div class="coach-content">
            <% if current_user.student_or_coach == "student" %>
          <div class="coach-content-for-student">
            <div class="coach-content-top">
              <b class="top-item">コーチ</b>
            </div>
              <ul>
                <li><%= link_to "自分のコーチ一覧", tweets_path, class: "side-bar-content" %></li>
                <li><%= link_to "アンケート", tweets_path, class: "side-bar-content" %></li>
                <li><%= link_to "コーチになる", edit_user_path(current_user.id), class: "side-bar-content" %></li>
              </ul>
          </div>
            <% elsif current_user.student_or_coach == "coach"   %>
          <div class="coach-content-for-coach">
            <div class="coach-content-top">
              <b class="top-item">コーチ</b>
            </div>
              <ul>
                <li><%= link_to "自分の生徒一覧", tweets_path, class: "side-bar-content" %></li>
                <li><%= link_to "主体的な学びへのシート", tweets_path, class: "side-bar-content" %></li>
                <li><%= link_to "コーチランキング", tweets_path, class: "side-bar-content" %></li>
              </ul>
          </div>
            <% end %>
        </div> 
            <% if current_user.admin == "true" %>
        <div class="admin-content">
          <div class="admin-content-top">
            <b class="top-item">運営</b>
          </div>
            <ul>
              <li> <%= link_to "講師承認", operations_path , class: "side-bar-content" %></li>
            </ul>
        </div>
            <% end %>
        <% end %>
      </div>

app/views/tweets/create.html.erb
<div class="contents-row">
  <div class="success">
    <h3>投稿が完了しました。</h3>
     <%= link_to "投稿一覧へ戻る", tweets_path, class: "btn" %>
  </div>
</div>

app/views/tweets/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
     <%= link_to "投稿一覧へ戻る", tweets_path, class: "btn" %>
  </div>
</div>

app/views/tweets/edit.html.erb
    <%= render partial: "tweets/header" %>
    <div class="middle-content">
      <%= render partial: "tweets/sidebar" %>
      <div class="main">
        <div class="post-function">
         <% if user_signed_in? %>
           <% if current_user.user_icon.presence %>
            <div>
             <%= link_to image_tag(current_user.user_icon, class: 'icon' )  , root_path  %>
            </div>
          <% else %>  
           <div>    
             <%= link_to image_tag("/images/icon.png", class: 'account-icon' )  , root_path  %>
           </div>
          <% end %> 
          <%= form_with(model: @tweet, local: true) do |form| %>
            <%= form.text_area :tweet,placeholder: "面白いことや、不思議に思ったことはあったかな？", class: "tweet-content-form" %>
            <%= form.submit "つぶやく", class: "tweet-send" %>
          <%end%>
         <% end %>
        </div>        
      </div>
    </div>
    <%= render partial: "tweets/footer" %>

app/views/tweets/index.html.erb
    <%= render partial: "header" %>
    <div class="middle-content">
      <%= render partial: "sidebar" %>
      <div class="main">
       <%= render partial: "postfunction" %>
        <div class="contents-row">
          <% @tweets.each do |tweet| %>
            <%= render partial: "postindex", locals: { tweet: tweet } %>
          <% end %>
        </div>
      </div>
      
    </div>
    <%= render partial: "footer" %>

app/views/tweets/new.html.erb
    <%= render partial: "header" %>
    <div class="middle-content">
      <%= render partial: "sidebar" %>
      <div class="main">
       <%= render partial: "postfunction" %>
      </div>
    </div>
    <%= render partial: "footer" %>

app/views/tweets/show.html.erb
    <%= render partial: "tweets/header" %>
    <div class="middle-content">
      <%= render partial: "tweets/sidebar" %>
      <div class="main">
        <div class="contents-row">
          <%= render partial: "tweets/postindex", locals: { tweet: @tweet } %>
          <div class="comment-index">
            <% if user_signed_in? %>
              <%= form_with(model: [@tweet, @comment], local: true) do |form| %>
                <%= form.text_area :text, placeholder: "コメントする", rows: "2", class: "comment-content-form" %>
                <%= form.submit "投稿する", class: "comment-submit" %><br><br>
              <%end%>
            <%else%>
             <strong><p>※※※　「いいね」やコメントの投稿には新規登録/ログインが必要です　※※※</p></strong>
            <%end%>
            <%= link_to "戻る", tweets_path, class:  "research-send-back" %> 
            <div class="flex">
            <div class="comments">
             <h2>【トータルいいね数】 <%= @likes.count %> </h2>
              <h4>いいねしたユーザの一覧</h4>
              <% @likes.each do |like| %>
               <% if like.user.present? %>
                <p>
                  <strong><%= link_to like.user.Nickname, "/users/#{like.user_id}" %></strong>
                </p>
               <% end %>
              <% end %>
            </div>
            <div class="comments">
              <h2>【コメント一覧】</h2>
              <% @comments.each do |comment| %>
                <% if comment.user.present? %>
                <p>
                  <strong><%= link_to comment.user.Nickname, "/users/#{comment.user_id}" %></strong>
                  <%= comment.text %>
                </p>
                <% end %>
              <% end %>
            </div>
            </div>
          </div>
        </div>
      </div>

    </div>

    <%= render partial: "tweets/footer" %>

app/views/tweets/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>更新が完了しました。</h3>
     <%= link_to "投稿一覧へ戻る", tweets_path, class: "btn" %>
  </div>
</div>