config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: {   registrations: 'users/registrations',
    sessions: 'users/sessions' }
  
  root to: 'lp#index'
  resources :tweets do
    resources :comments,only: [:index,:create] do
    end
      resources :tweet_likes, only: [:index,:create,:destroy]
  end
  resources :user,only: [:show,:edit,:update] do
    resources :chat_room, only: [:new,:create] do
      resources :chats, only: [:index, :create]
    end
  end
  resources :operations , only: [:index,:edit]
  resources :researches do
    resources :research_comments, only: [:index,:create]
    resources :research_likes, only: [:index,:create,:destroy]
    collection do
      get 'my_research'
      get 'search'
      get 'my_search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :chats
  has_many :room_users
  has_many :users, through: :room_users
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  belongs_to :tweet
end

app/models/research.rb
class Research < ApplicationRecord
  validates :research_url,presence: true
  validates :research_title,presence: true,length: { maximum: 50 }
  validates :research_summary,presence: true,length: { maximum: 500 }
  belongs_to :user
  has_many :research_comments
  has_many :research_likes

  def self.search(search_key)
      Research.where('research_title LIKE(?)', "%#{search_key}%")
  end 

  def self.my_search(search_key,current_user_id)
    Research.where('research_title LIKE(?)', "%#{search_key}%").where('user_id LIKE(?)', "%#{current_user_id}%")
end 

end

app/models/research_comment.rb
class ResearchComment < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  belongs_to :research
end

app/models/research_like.rb
class ResearchLike < ApplicationRecord
  belongs_to :user
  belongs_to :research
  validates_uniqueness_of :research_id, scope: :user_id
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :tweet, presence: true
  belongs_to :user
  has_many :comments
  has_many :tweet_likes
end

app/models/tweet_like.rb
class TweetLike < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets,dependent: :destroy
  has_many :researches,dependent: :destroy
  has_one_attached :user_icon,dependent: :destroy
  has_one_attached :user_identification,dependent: :destroy
  has_many :comments,dependent: :destroy
  has_many :research_comments,dependent: :destroy
  has_many :research_likes,dependent: :destroy
  has_many :tweet_likes,dependent: :destroy
  has_many :room_users
  has_many :chat_rooms, through: :room_users
  has_many :chats
  validates :Nickname, presence: true,uniqueness: true,length: { maximum: 15 }
  validates :password, length: { maximum: 30 }
  validates :password_confirmation, length: { maximum: 30 }
  validates :hobby, length: { maximum: 100 }
  validates :aWord, length: { maximum: 100 }

  def already_liked?(research)
    self.research_likes.exists?(research_id: research.id)
  end

  def tweet_already_liked?(tweet)
    self.tweet_likes.exists?(tweet_id: tweet.id)
  end


end

app/controllers/lp_controller.rb
class LpController < ApplicationController

  def index
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  before_action :return_index

  def show
    @user = User.find(params[:id])
    @tweets = User.find(params[:id]).tweets.order(created_at: :desc)
    @tweet = Tweet.new
  end

  def edit
    @coach = User.find(params[:id])
  end

  def update
    
    if coach_params[:FirstName].blank? || coach_params[:LastName].blank? || coach_params[:user_identification].blank? || coach_params[:university].blank? || coach_params[:department].blank? || coach_params[:major].blank?
      redirect_to edit_user_path(current_user.id),flash: {error_coach: "各項目の入力は必須です。"}
    else
      @coach = User.find(params[:id]) 
      @coach.update(coach_params)
    end
  end

  private

  def return_index
    unless user_signed_in?
      redirect_to "/"
    end
  end

  def coach_params
    params.require(:user).permit(:FirstName,:LastName,:user_icon,:university,:department,:major,:user_identification,:Nickname,:email)
  end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  #アカウント登録後のリダイレクト先
def after_sign_up_path_for(resource)
  tweets_path
end

#アカウント編集後のリダイレクト先
def after_update_path_for(resource)
  tweets_path
end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
 #ログイン後のリダイレクト先
def after_sign_in_path_for(resource)
  tweets_path
end 
#ログアウト後のリダイレクト先
def after_sign_out_path_for(resource)
  root_path
end 
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_room_helper.rb
module ChatRoomHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lp_helper.rb
module LpHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/helpers/researches_helper.rb
module ResearchesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/edit.html.erb
<div class="contents_edit_request">
 <div class="left_back">
 </div>
  <div class="middle_back">
     <p class="title">講師申請</p>
     <%= form_with(model: @coach, local: true,method: :patch) do |f| %>
      <div class="field_error"><%= flash[:error_coach] %></div> 
       <div class="field">
          <%= f.label :"姓" %><br />
          <%= f.text_field :FirstName, autofocus: true,maxlength: "50" %>
       </div>
        <div class="field">
          <%= f.label :"名" %><br />
          <%= f.text_field :LastName, autofocus: true,maxlength: "50" %>
       </div>
       <div class="field">
           <p>ユーザアイコン</p>
           <p class="warn">(ご自身の顔が写った写真をアイコンに設定して下さい)</p><br />
           <% if current_user.user_icon.presence %>
             <div>
              <%= image_tag(current_user.user_icon, class: 'icon') %>
             </div>
           <% else %>  
             <div>    
              <%= image_tag("/images/icon.png", class: 'headder-account')  %>
            </div>
           <% end %>
           <%= f.label :"ユーザアイコンの変更が必要な場合は画像ファイルを選択▼" %><br/><br>
           <%= f.file_field :user_icon %>
       </div>
        <div class="field">
          <%= f.label :"大学名" %><br />
          <%= f.text_field :university, autofocus: true,maxlength: "50" %>
       </div>
         <div class="field">
          <%= f.label :"学部" %><br />
          <%= f.text_field :department, autofocus: true,maxlength: "50" %>
       </div>
         <div class="field">
          <%= f.label :"学科" %><br />
          <%= f.text_field :major, autofocus: true,maxlength: "50" %>
       </div>
        <div class="field">
         <p class="warn">【本人認証】ご自身の顔と学生証が一緒に写った画像をアップロード</p>
           <%= f.file_field :user_identification %>
        </div>
        <div class="field">
           <%= f.hidden_field :Nickname ,value: current_user.Nickname %>
        </div>
        <div class="field">
           <%= f.hidden_field :email ,value: current_user.email %>
        </div>
       <div class="field">
           <%= f.submit "申請する",class: "btn-n btn--orange btn--shadow" %>
           <%= link_to "戻る", tweets_path, class: "btn btn--blue btn--shadow" %>
      </div>
    <% end %>
  </div>
   <div class="right_back">
 </div>
</div>

app/views/user/show.html.erb
    <%= render partial: "tweets/header" %>
    <div class="middle-content">
      <%= render partial: "tweets/sidebar" %>
      <div class="main">
        <div class="contents-row">
          <div class="profile">
            <h1>プロフィール</h1>
            <h3><%= "ニックネーム:#{@user.Nickname}" %></h3>
            <h3><%= "一言:#{@user.aWord}" %></h3>
            <div class="message_link">
              <%= link_to image_tag("/images/message.png", class:"message"),new_user_chat_room_path(@user.id) %>
              <p>⏪一緒に研究するには、まずはメッセージを送ろう！</p>            
            </div>
          </div>
          <% @tweets.each do |tweet| %>
            <%= render partial: "tweets/postindex", locals: { tweet: tweet } %>
          <% end %>
        </div>
      </div>
      
    </div>
    <%= render partial: "tweets/footer" %>

app/views/user/update.html.erb
<div class="contents row">
  <div class="success">
    <h1>講師申請が完了しました。</h1>
    <h1 class="warn">申請が承認されましたら、ステータスが更新され、ユーザ名の左側に講師アイコンが付与されます。</h1>
    <%= link_to "戻る", tweets_path, class: "btn" %>
  </div>
</div>