config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: {   registrations: 'users/registrations',
    sessions: 'users/sessions' }
  
  root to: 'lp#index'
  resources :tweets do
    resources :comments,only: [:index,:create] do
    end
      resources :tweet_likes, only: [:index,:create,:destroy]
  end
  resources :user,only: [:show,:edit,:update] do
    resources :chat_room, only: [:new,:create] do
      resources :chats, only: [:index, :create]
    end
  end
  resources :operations , only: [:index,:edit]
  resources :researches do
    resources :research_comments, only: [:index,:create]
    resources :research_likes, only: [:index,:create,:destroy]
    collection do
      get 'my_research'
      get 'search'
      get 'my_search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :chats
  has_many :room_users
  has_many :users, through: :room_users
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  belongs_to :tweet
end

app/models/research.rb
class Research < ApplicationRecord
  validates :research_url,presence: true
  validates :research_title,presence: true,length: { maximum: 50 }
  validates :research_summary,presence: true,length: { maximum: 500 }
  belongs_to :user
  has_many :research_comments
  has_many :research_likes

  def self.search(search_key)
      Research.where('research_title LIKE(?)', "%#{search_key}%")
  end 

  def self.my_search(search_key,current_user_id)
    Research.where('research_title LIKE(?)', "%#{search_key}%").where('user_id LIKE(?)', "%#{current_user_id}%")
end 

end

app/models/research_comment.rb
class ResearchComment < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  belongs_to :research
end

app/models/research_like.rb
class ResearchLike < ApplicationRecord
  belongs_to :user
  belongs_to :research
  validates_uniqueness_of :research_id, scope: :user_id
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :tweet, presence: true
  belongs_to :user
  has_many :comments
  has_many :tweet_likes
end

app/models/tweet_like.rb
class TweetLike < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets,dependent: :destroy
  has_many :researches,dependent: :destroy
  has_one_attached :user_icon,dependent: :destroy
  has_one_attached :user_identification,dependent: :destroy
  has_many :comments,dependent: :destroy
  has_many :research_comments,dependent: :destroy
  has_many :research_likes,dependent: :destroy
  has_many :tweet_likes,dependent: :destroy
  has_many :room_users
  has_many :chat_rooms, through: :room_users
  has_many :chats
  validates :Nickname, presence: true,uniqueness: true,length: { maximum: 15 }
  validates :password, length: { maximum: 30 }
  validates :password_confirmation, length: { maximum: 30 }
  validates :hobby, length: { maximum: 100 }
  validates :aWord, length: { maximum: 100 }

  def already_liked?(research)
    self.research_likes.exists?(research_id: research.id)
  end

  def tweet_already_liked?(tweet)
    self.tweet_likes.exists?(tweet_id: tweet.id)
  end


end

app/controllers/lp_controller.rb
class LpController < ApplicationController

  def index
  end

end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController

  before_action :return_index

  def index
    @users = User.all
  end

  def edit
    user = User.find(params[:id])
    user.student_or_coach = "coach"
    user.save
    redirect_to operations_path
  end

  private

  def return_index
    unless user_signed_in?
      redirect_to "/"
    end
  end

end

app/helpers/chat_room_helper.rb
module ChatRoomHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lp_helper.rb
module LpHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/helpers/researches_helper.rb
module ResearchesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/operations/index.html.erb
<%= render partial: "tweets/header" %>
<div class="middle-content">
  <%= render partial: "tweets/sidebar" %>
  <div class="main">
    <p class="title-ope">講師希望ユーザ一覧</p>
   <% @users.each do |user| %>
     <% if user.user_identification.attached? && user.student_or_coach == "student"  %>
     <div class="content-post-area-ope">
         <div class=flex>
          <p class="contributor-name"><%= user.Nickname %></p>
          <% if user.user_icon.attached?  %>
           <%= link_to image_tag(user.user_icon, class: 'icon' )  , root_path  %>
          <% else %>
           <%= image_tag("/images/icon.png", class: 'headder-account' ) %>
          <% end %>
          <p class="contributor-name"><%= "【本名】 " + user.FirstName + user.LastName %></p>
          <p class="contributor-name"><%= "【大学】 " + user.university %></p>
          <p class="contributor-name"><%= "【学部】 " + user.department %></p>
          <p class="contributor-name"><%= "【学科】 " + user.major %></p>
         </div>
         <div class="flex">
          <p class="contributor-name">本人証明画像</p>
           <div>
             <%= image_tag(user.user_identification, class: 'identification_icon') %>
           </div>
           <div class="auth">
             <%= link_to "講師として承認する"  , edit_operation_path(user.id) ,class: "btn btn--blue btn--shadow" %>
           </div>
         </div>
    </div>
   <% end %>     
   <% end %>
  </div>
</div>
<%= render partial: "tweets/footer" %>